### PR TITLE
Inject silent audio element into iOS PWA's to prevent destruction of the DOM when suspended offscreen

### LINKED ISSUE #124: iOS: System playback controls fail to un-pause tracks when app is not open
1. Start playback
2. Turn off phone
3. Open lock screen, pause using the "payback widget"
4. Now, "Play"
5. Bug: Track does not play

### PR DESCRIPTION
**Pull request by JacksonKearl**
Fixes #124.

It's not the prettiest, but I've done what I can to make it as selectively applied as possible. In my testing it does correctly cause the playback to be resumable via the native UI's when paused and the application is in the background and/or the phone is locked, which was not previously possible.

### CODE REVIEW

**Comment by jwkent** [comment]
HI Jackson,
I deployed your changes to the QA server and am seeing a failure. I will leave it here for a few days for you to debug and let me know what is wrong. 

http://thenarrowpath.wvss.biz/    (QA)

> Error detected by Application Firewall. Please contact support if you have any questions.

John

**Comment by jwkent** [comment]
image

**Comment by jwkent** [comment]
QA server worked fine before your commit.

**Comment by JacksonKearl** [comment]
Hm. I see these errors when I try to load the QA domain. It's not immediately obvious how my changes could have caused this, let's revet my work for now to be sure that the errors can be attributed to it, then we can move forward with perhaps adjusting the way the changes are implemented to resolve these issues. (Maybe `data:` urls or appending to the DOM via JS are blocked by some anti-"hacking" filter based on the screenshot you provided?)

image

**Pull request merged**
