### PR TITLE
Rewrite liveRadioTimeCheck.js to account for Daylight Savings

### PR DESCRIPTION
**Pull request by javierxio**
@benjkent I rewrote this code to account for daylight savings which the time changes twice a year. I have tested this on my local machine. Please also see if you can accept it. Thanks.

### CODE REVIEW

**Comment by JacksonKearl** [comment]
It would perhaps be easier to use the `Intl` builtin object, which is better designed for this operation: 
```js
const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: "America/Los_Angeles", 
    hour: "numeric", 
    hour12: false, 
    weekday: 'long',
}).formatToParts(new Date())

const day = parts.find(p => p.type === 'weekday')
const hour = parts.find(p => p.type === 'hour')

return hour.value === 13 && day.value !== 'Saturday' && day.value !== 'Sunday'
```

**Comment by javierxio** [comment]
@JacksonKearl thanks for the code. it seems working on my side. You may want to create a pull request and I can close this one?

**Comment by JacksonKearl** [comment]
I'm not sure exactly how to run this project, does it work with VS Code or do I need a Visual Studio setup?

**Comment by JacksonKearl** [comment]
Okay I've been able to build the basic skeleton of the app, but it's missing a lot of CSS and all the content. Any ideas on how to get this working beyond a basic `dotnet watch`?

**Comment by JacksonKearl** [comment]
Ah, on macOS the `AudioWebApp.Client.styles.css` is case sensitive.

**Comment by javierxio** [comment]
I will close this PR and can be replaced by https://github.com/jwkent/AudioWebApp/pull/123

**Comment by benjkent** [comment]
Thanks for all the work. Looks good, I will test it on Monday and Tuesday.
    On Tuesday, April 30, 2024 at 11:32:17 AM PDT, javierxio ***@***.***> wrote:  
 
 


I will close this PR and can be replaced by #123

**Pull request closed without merging**
